sudo: required  # see https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
dist: trusty
branches:
  only:
    - master
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install graphviz -y
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
services:
  - postgresql
script:
  - coverage run -m pytest -v
after_success:
  - codecov
notifications:
    email:
        on_success: change
        on_failure: always
